

apiVersion: v1
kind: Service
metadata:
  name: devnull-svc
spec:
  type: NodePort
  ports:
    - name: devnull-port
      port: 80
      targetPort: 8082
      protocol: TCP
  selector:
    app: devnull

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: devnull
  labels:
    app: devnull
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: devnull
    spec:
      containers:
         - name: devnull
           image: eu.gcr.io/javabin-prod/devnull:latest
           imagePullPolicy: Always
           ports:
             - name: http
               containerPort: 8082
           env:
             - name: DB_HOST
               value: "127.0.0.1"
             - name: DB_PORT
               value: "3306"
             - name: DB_USER
               valueFrom:
                 secretKeyRef:
                   name: devnull-db-credentials
                   key: username
             - name: DB_PASSWORD
               valueFrom:
                 secretKeyRef:
                   name: devnull-db-credentials
                   key: password
             - name: SLEEPING_PILL_URL
               valueFrom:
                 configMapKeyRef:
                   name: devnull-config
                   key: sleepingpill.url
         - name: devnull-db-proxy
           image: gcr.io/cloudsql-docker/gce-proxy:1.11
           command: ["/cloud_sql_proxy",
                      "-instances=$(DB_INSTANCES)",
                      "-credential_file=/secrets/cloudsql/credentials.json"]
           env:
             - name: DB_INSTANCES
               valueFrom:
                 secretKeyRef:
                   name: devnull-db-credentials
                   key: db_instance
           volumeMounts:
             - name: devnull-cloudsql-credentials
               mountPath: /secrets/cloudsql
               readOnly: true
      volumes:
        - name: devnull-cloudsql-credentials
          secret:
            secretName: devnull-cloudsql-credentials
